import { StyleSheet } from "react-native";

import { Colors, Fonts, Spacing } from "@/constants/theme";

const styles = StyleSheet.create({
  content: {
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.three,
  },
  title: {
    maxWidth: 320,
    textAlign: "center",
    fontFamily: Fonts.logo,
    fontSize: 38,
    lineHeight: 44,
    letterSpacing: 0.1,
  },
  trackCard: {
    alignItems: "center",
    width: "100%",
    maxWidth: 340,
    borderRadius: 56,
    backgroundColor: Colors.backgroundElement,
    paddingHorizontal: Spacing.four,
    paddingVertical: Spacing.five,
    gap: Spacing.three,
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  progressSection: {
    width: "100%",
    gap: Spacing.two,
  },
  progressTrack: {
    width: "100%",
    height: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: Colors.text,
    borderRadius: 999,
    backgroundColor: Colors.background,
  },
  progressFill: {
    height: "100%",
    backgroundColor: Colors.backgroundSelected,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  timeText: {
    fontFamily: Fonts.lato.bold,
    fontSize: 12,
    lineHeight: 16,
  },
  cardControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 240,
  },
  buttonStack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 240,
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: Colors.text,
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  playButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  primaryButton: {
    backgroundColor: Colors.backgroundSelected,
  },
  secondaryButton: {
    backgroundColor: Colors.backgroundElement,
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonDisabled: {
    opacity: 0.4,
  },
  buttonText: {
    color: Colors.textOnSelected,
    fontFamily: Fonts.lato.bold,
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
  },
  secondaryButtonText: {
    color: Colors.text,
  },
  playIcon: {
    width: 0,
    height: 0,
    marginLeft: Spacing.one,
    borderTopWidth: 12,
    borderBottomWidth: 12,
    borderLeftWidth: 19,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: Colors.textOnSelected,
  },
  pauseIcon: {
    flexDirection: "row",
    gap: Spacing.two,
  },
  pauseBar: {
    width: 6,
    height: 24,
    borderRadius: 4,
    backgroundColor: Colors.text,
  },
  previousIcon: {
    flexDirection: "row",
    alignItems: "center",
  },
  nextIcon: {
    flexDirection: "row",
    alignItems: "center",
  },
  skipBar: {
    width: 4,
    height: 24,
    borderRadius: 2,
    backgroundColor: Colors.text,
  },
  previousTriangle: {
    width: 0,
    height: 0,
    borderTopWidth: 12,
    borderBottomWidth: 12,
    borderRightWidth: 18,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderRightColor: Colors.text,
  },
  nextTriangle: {
    width: 0,
    height: 0,
    borderTopWidth: 12,
    borderBottomWidth: 12,
    borderLeftWidth: 18,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: Colors.text,
  },
  stopIcon: {
    width: 22,
    height: 22,
    borderRadius: 4,
    backgroundColor: Colors.text,
  },
  heartIcon: {
    color: Colors.text,
    fontFamily: Fonts.lato.bold,
    fontSize: 26,
    lineHeight: 30,
    textAlign: "center",
  },
  favoriteHeart: {
    color: Colors.text,
  },
  welcome: {
    textAlign: "center",
    fontFamily: Fonts.lato.light,
    fontSize: 14,
    lineHeight: 20,
  },
  description: {
    maxWidth: 260,
    marginTop: Spacing.one,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Fonts.lato.light,
  },
});

export default styles;
