import { StyleSheet } from "react-native";

import { ButtonRadius, Colors, Fonts, Spacing } from "@/constants/theme";

const styles = StyleSheet.create({
  safeArea: {
    justifyContent: "flex-start",
  },
  content: {
    alignItems: "center",
    gap: Spacing.four,
    paddingVertical: Spacing.five,
  },
  title: {
    maxWidth: 320,
    textAlign: "center",
    fontFamily: Fonts.logo,
    fontSize: 38,
    lineHeight: 44,
    letterSpacing: 0.1,
  },
  buttonStack: {
    width: "100%",
    maxWidth: 240,
    gap: Spacing.two,
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
    borderRadius: ButtonRadius,
    borderWidth: 1,
    borderColor: Colors.text,
    backgroundColor: Colors.backgroundSelected,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
  },
  secondaryButton: {
    backgroundColor: Colors.backgroundElement,
  },
  buttonPressed: {
    opacity: 0.7,
  },
  buttonText: {
    color: Colors.textOnSelected,
    fontFamily: Fonts.lato.bold,
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
  },
  secondaryButtonText: {
    color: Colors.text,
  },
  favoriteHeart: {
    color: Colors.text,
  },
  welcome: {
    textAlign: "center",
    fontFamily: Fonts.lato.light,
    fontSize: 14,
    lineHeight: 20,
  },
  description: {
    maxWidth: 260,
    marginTop: Spacing.one,
    textAlign: "center",
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Fonts.lato.light,
  },
  emptyText: {
    maxWidth: 260,
    textAlign: "center",
    fontFamily: Fonts.lato.light,
    fontSize: 14,
    lineHeight: 20,
  },
  list: {
    width: "100%",
    maxWidth: 340,
    gap: Spacing.three,
  },
  songCard: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.three,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: Colors.text,
    backgroundColor: Colors.backgroundElement,
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
    shadowColor: Colors.text,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 5,
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: Colors.text,
    backgroundColor: Colors.backgroundElement,
  },
  playIcon: {
    width: 0,
    height: 0,
    marginLeft: 3,
    borderTopWidth: 8,
    borderBottomWidth: 8,
    borderLeftWidth: 13,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: Colors.text,
  },
  songDetails: {
    flex: 1,
  },
  songTitle: {
    fontFamily: Fonts.lato.bold,
    fontSize: 18,
    lineHeight: 24,
  },
  songDescription: {
    marginTop: Spacing.one,
    fontFamily: Fonts.lato.light,
    fontSize: 14,
    lineHeight: 20,
  },
  deleteIcon: {
    width: 18,
    height: 22,
    alignItems: "center",
  },
  deleteLid: {
    width: 16,
    height: 3,
    marginBottom: 2,
    borderRadius: 2,
    backgroundColor: Colors.text,
  },
  deleteCan: {
    width: 14,
    height: 16,
    flexDirection: "row",
    justifyContent: "center",
    gap: 3,
    borderRadius: 2,
    borderWidth: 2,
    borderTopWidth: 0,
    borderColor: Colors.text,
    paddingTop: 3,
  },
  deleteLine: {
    width: 2,
    height: 9,
    borderRadius: 1,
    backgroundColor: Colors.text,
  },
});

export default styles;
