/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.utils`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/module/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/HomeScreen/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/PlayerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/PlayerScreen/PlayerScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/module/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.utils`; params?: Router.UnknownOutputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.styles`; params?: Router.UnknownOutputParams; } | { pathname: `/module/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/module/HomeScreen/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/module/PlayerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/module/PlayerScreen/PlayerScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/module/WelcomeScreen/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/module/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/module/WelcomeScreen/WelcomeScreen.utils${`?${string}` | `#${string}` | ''}` | `/module/WelcomeScreen/WelcomeScreen.styles${`?${string}` | `#${string}` | ''}` | `/module/HomeScreen${`?${string}` | `#${string}` | ''}` | `/module/HomeScreen/HomeScreen${`?${string}` | `#${string}` | ''}` | `/module/PlayerScreen${`?${string}` | `#${string}` | ''}` | `/module/PlayerScreen/PlayerScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.utils`; params?: Router.UnknownInputParams; } | { pathname: `/module/WelcomeScreen/WelcomeScreen.styles`; params?: Router.UnknownInputParams; } | { pathname: `/module/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/HomeScreen/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/PlayerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/module/PlayerScreen/PlayerScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
